version: '3'

services:
    web:
        build: .
        container_name: main_web
        ports:
            - 5006:5000
        volumes:
            - ./data/data_file.json:/data_file.json
    redis:
        image: redis:latest
        ports:
            - 6386:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: ["redis-server","/redis.conf"]

