apiVersion: v1
kind: Service
metadata:
  name: kchristi-test-redis-service
  labels:
    username: kchristi
    env: test
spec:
  type: ClusterIP
  selector:
    app: kchristi-test-redis
  ports:
  - name: kchristi-test-redis-service
    port: 6379
    targetPort: 6379
