apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kchristi-test-redis-pvc-data
  labels:
    username: kchristi
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
